import { COIN_TYPE, Network } from '@interest-protocol/sui-amm-sdk';

export const COIN_MARKET_CAP_ID_RECORD = {
  [Network.DEVNET]: {
    [COIN_TYPE[Network.DEVNET].BNB]: 1839,
    [COIN_TYPE[Network.DEVNET].ETH]: 1027,
    [COIN_TYPE[Network.DEVNET].BTC]: 1,
    [COIN_TYPE[Network.DEVNET].USDT]: 825,
    [COIN_TYPE[Network.DEVNET].USDC]: 3408,
    [COIN_TYPE[Network.DEVNET].SUI]: 20947,
    [COIN_TYPE[Network.DEVNET].IPX]: -1,
  },
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].BNB]: 1839,
    [COIN_TYPE[Network.TESTNET].ETH]: 1027,
    [COIN_TYPE[Network.TESTNET].BTC]: 1,
    [COIN_TYPE[Network.TESTNET].USDT]: 825,
    [COIN_TYPE[Network.TESTNET].USDC]: 3408,
    [COIN_TYPE[Network.TESTNET].SUI]: 20947,
    [COIN_TYPE[Network.TESTNET].IPX]: -1,
  },
  [Network.MAINNET]: {
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT]: 825,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC]: 3408,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT]: 825,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC]: 3408,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH]: 1027,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH]: 1027,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB]: 1839,
    [COIN_TYPE[Network.MAINNET].SUI]: 20947,
  },
};
