export enum COMMON_STRINGS {
  colon = ': ',
  max = 'max',
  tvl = 'TVL',
  ltv = 'LTV',
  apr = 'APR',
  allocation = 'allocation',
  number = 'nº',
  id = 'id',
  plus = '+',
  minus = '-',
  per = '/',
  token = 'token',
  arrowLeft = '←',
  dinero = 'dinero',
  stableEquation = 'K = 3XY + 3XY',
  volatileEquation = 'K = Y * X',
  ethLink = 'https://ethereum.org/en/',
  bnbLink = 'https://www.bnbchain.org/en',
  percentage = '%',
  dnr = 'DNR',
  faucet = 'faucet',
  dex = 'dex',
  feedback = 'feedback',
  bnbt = 'BNBT',
  rinkeby = 'Rinkeby',
  bnbMain = 'BNB Main Net',
  bnbTest = 'BNB Test Net',
  lp = 'LP',
  rangeOf100 = '% of 100%',
  farms = 'farms',
}
