import { CoinData } from '@/interface';

import { COIN_FARM, COIN_POOL, COIN_TYPE, COINS } from './coins';
import { Network } from './network';

export const FARMS_RECORD = {
  [Network.DEVNET]: {
    [COIN_TYPE[Network.DEVNET].IPX]: {
      farmType: COIN_TYPE[Network.DEVNET].IPX,
      farmObjectId: COIN_FARM[Network.DEVNET].IPX,
      poolObjectId: COIN_POOL[Network.DEVNET].V_LP_ETH_IPX,
      lpCoin: COINS[Network.DEVNET].IPX,
      coin0: COINS[Network.DEVNET].ETH,
      coin1: COINS[Network.DEVNET].IPX,
      isSingleCoin: true,
      id: 0,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.DEVNET].V_LP_SUI_ETH]: {
      farmType: COIN_TYPE[Network.DEVNET].V_LP_SUI_ETH,
      farmObjectId: COIN_FARM[Network.DEVNET].SUI_ETH,
      poolObjectId: COIN_POOL[Network.DEVNET].V_LP_SUI_ETH,
      lpCoin: COINS[Network.DEVNET].V_LP_SUI_ETH,
      coin0: COINS[Network.DEVNET].SUI,
      coin1: COINS[Network.DEVNET].ETH,
      isSingleCoin: false,
      id: 1,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.DEVNET].V_LP_ETH_IPX]: {
      farmType: COIN_TYPE[Network.DEVNET].V_LP_ETH_IPX,
      farmObjectId: COIN_FARM[Network.DEVNET].ETH_IPX,
      poolObjectId: COIN_POOL[Network.DEVNET].V_LP_ETH_IPX,
      lpCoin: COINS[Network.DEVNET].V_LP_ETH_IPX,
      coin0: COINS[Network.DEVNET].ETH,
      coin1: COINS[Network.DEVNET].IPX,
      isSingleCoin: false,
      id: 2,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.DEVNET].V_LP_BTC_ETH]: {
      farmType: COIN_TYPE[Network.DEVNET].V_LP_BTC_ETH,
      farmObjectId: COIN_FARM[Network.DEVNET].BTC_ETH,
      poolObjectId: COIN_POOL[Network.DEVNET].V_LP_BTC_ETH,
      lpCoin: COINS[Network.DEVNET].V_LP_BTC_ETH,
      coin0: COINS[Network.DEVNET].BTC,
      coin1: COINS[Network.DEVNET].ETH,
      isSingleCoin: false,
      id: 3,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.DEVNET].V_LP_BNB_ETH]: {
      farmType: COIN_TYPE[Network.DEVNET].V_LP_BNB_ETH,
      farmObjectId: COIN_FARM[Network.DEVNET].BNB_ETH,
      poolObjectId: COIN_POOL[Network.DEVNET].V_LP_BNB_ETH,
      lpCoin: COINS[Network.DEVNET].V_LP_BNB_ETH,
      coin0: COINS[Network.DEVNET].BNB,
      coin1: COINS[Network.DEVNET].ETH,
      isSingleCoin: false,
      id: 4,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.DEVNET].V_LP_ETH_USDT]: {
      farmType: COIN_TYPE[Network.DEVNET].V_LP_ETH_USDT,
      farmObjectId: COIN_FARM[Network.DEVNET].ETH_USDT,
      poolObjectId: COIN_POOL[Network.DEVNET].V_LP_ETH_USDT,
      lpCoin: COINS[Network.DEVNET].V_LP_ETH_USDT,
      coin0: COINS[Network.DEVNET].ETH,
      coin1: COINS[Network.DEVNET].USDT,
      isSingleCoin: false,
      id: 5,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.DEVNET].V_LP_ETH_USDC]: {
      farmType: COIN_TYPE[Network.DEVNET].V_LP_ETH_USDC,
      farmObjectId: COIN_FARM[Network.DEVNET].ETH_USDC,
      poolObjectId: COIN_POOL[Network.DEVNET].V_LP_ETH_USDC,
      lpCoin: COINS[Network.DEVNET].V_LP_ETH_USDC,
      coin0: COINS[Network.DEVNET].ETH,
      coin1: COINS[Network.DEVNET].USDC,
      isSingleCoin: false,
      id: 6,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.DEVNET].V_LP_DAI_ETH]: {
      farmType: COIN_TYPE[Network.DEVNET].V_LP_DAI_ETH,
      farmObjectId: COIN_FARM[Network.DEVNET].DAI_ETH,
      poolObjectId: COIN_POOL[Network.DEVNET].V_LP_DAI_ETH,
      lpCoin: COINS[Network.DEVNET].V_LP_DAI_ETH,
      coin0: COINS[Network.DEVNET].DAI,
      coin1: COINS[Network.DEVNET].ETH,
      isSingleCoin: false,
      id: 7,
      isLive: true,
      stable: false,
    },
  },
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].IPX]: {
      farmType: COIN_TYPE[Network.TESTNET].IPX,
      farmObjectId: COIN_FARM[Network.TESTNET].IPX,
      poolObjectId: COIN_POOL[Network.TESTNET].V_LP_ETH_IPX,
      lpCoin: COINS[Network.TESTNET].IPX,
      coin0: COINS[Network.TESTNET].ETH,
      coin1: COINS[Network.TESTNET].IPX,
      isSingleCoin: true,
      id: 0,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.TESTNET].V_LP_SUI_ETH]: {
      farmType: COIN_TYPE[Network.TESTNET].V_LP_SUI_ETH,
      farmObjectId: COIN_FARM[Network.TESTNET].SUI_ETH,
      poolObjectId: COIN_POOL[Network.TESTNET].V_LP_SUI_ETH,
      lpCoin: COINS[Network.TESTNET].V_LP_SUI_ETH,
      coin0: COINS[Network.TESTNET].SUI,
      coin1: COINS[Network.TESTNET].ETH,
      isSingleCoin: false,
      id: 1,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_IPX]: {
      farmType: COIN_TYPE[Network.TESTNET].V_LP_ETH_IPX,
      farmObjectId: COIN_FARM[Network.TESTNET].ETH_IPX,
      poolObjectId: COIN_POOL[Network.TESTNET].V_LP_ETH_IPX,
      lpCoin: COINS[Network.TESTNET].V_LP_ETH_IPX,
      coin0: COINS[Network.TESTNET].ETH,
      coin1: COINS[Network.TESTNET].IPX,
      isSingleCoin: false,
      id: 2,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.TESTNET].V_LP_BTC_ETH]: {
      farmType: COIN_TYPE[Network.TESTNET].V_LP_BTC_ETH,
      farmObjectId: COIN_FARM[Network.TESTNET].BTC_ETH,
      poolObjectId: COIN_POOL[Network.TESTNET].V_LP_BTC_ETH,
      lpCoin: COINS[Network.TESTNET].V_LP_BTC_ETH,
      coin0: COINS[Network.TESTNET].BTC,
      coin1: COINS[Network.TESTNET].ETH,
      isSingleCoin: false,
      id: 3,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.TESTNET].V_LP_BNB_ETH]: {
      farmType: COIN_TYPE[Network.TESTNET].V_LP_BNB_ETH,
      farmObjectId: COIN_FARM[Network.TESTNET].BNB_ETH,
      poolObjectId: COIN_POOL[Network.TESTNET].V_LP_BNB_ETH,
      lpCoin: COINS[Network.TESTNET].V_LP_BNB_ETH,
      coin0: COINS[Network.TESTNET].BNB,
      coin1: COINS[Network.TESTNET].ETH,
      isSingleCoin: false,
      id: 4,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDT]: {
      farmType: COIN_TYPE[Network.TESTNET].V_LP_ETH_USDT,
      farmObjectId: COIN_FARM[Network.TESTNET].ETH_USDT,
      poolObjectId: COIN_POOL[Network.TESTNET].V_LP_ETH_USDT,
      lpCoin: COINS[Network.TESTNET].V_LP_ETH_USDT,
      coin0: COINS[Network.TESTNET].ETH,
      coin1: COINS[Network.TESTNET].USDT,
      isSingleCoin: false,
      id: 5,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDC]: {
      farmType: COIN_TYPE[Network.TESTNET].V_LP_ETH_USDC,
      farmObjectId: COIN_FARM[Network.TESTNET].ETH_USDC,
      poolObjectId: COIN_POOL[Network.TESTNET].V_LP_ETH_USDC,
      lpCoin: COINS[Network.TESTNET].V_LP_ETH_USDC,
      coin0: COINS[Network.TESTNET].ETH,
      coin1: COINS[Network.TESTNET].USDC,
      isSingleCoin: false,
      id: 6,
      isLive: true,
      stable: false,
    },
    [COIN_TYPE[Network.TESTNET].V_LP_DAI_ETH]: {
      farmType: COIN_TYPE[Network.TESTNET].V_LP_DAI_ETH,
      farmObjectId: COIN_FARM[Network.TESTNET].DAI_ETH,
      poolObjectId: COIN_POOL[Network.TESTNET].V_LP_DAI_ETH,
      lpCoin: COINS[Network.TESTNET].V_LP_DAI_ETH,
      coin0: COINS[Network.TESTNET].DAI,
      coin1: COINS[Network.TESTNET].ETH,
      isSingleCoin: false,
      id: 7,
      isLive: true,
      stable: false,
    },
  },
};

export interface FarmMetadataType {
  farmType: string;
  lpCoin: CoinData;
  coin0: CoinData;
  coin1: CoinData;
  isSingleCoin: boolean;
  id: number;
  isLive: boolean;
  stable: boolean;
  poolObjectId: string;
  farmObjectId: string;
}
