export { default as CheckSVG } from './check';
export { default as DiscordSVG } from './discord';
export { default as DoorSVG } from './door';
export { default as GithubSVG } from './github';
export { default as LogoSVG } from './logo';
export { default as MediumSVG } from './medium';
export { default as TelegramSVG } from './telegram';
export { default as TimesSVG } from './times';
export { default as TwitterSVG } from './twitter';
