export const AddressZero =
  '0x0000000000000000000000000000000000000000000000000000000000000000';

export enum Rounding {
  ROUND_DOWN,
  ROUND_HALF_UP,
  ROUND_UP,
}

export const MAX_NUMBER_INPUT_VALUE = 9000000000000000;

export enum TOKEN_SYMBOL {
  BTC = 'BTC',
  ETH = 'ETH',
  BNB = 'BNB',
  USDC = 'USDC',
  USDT = 'USDT',
  SUI = 'SUI',
  IPX = 'IPX',
  V_LP_SUI_ETH = 'vSUI-ETH',
  V_LP_BTC_ETH = 'vBTC-ETH',
  V_LP_BNB_ETH = 'vBNB-ETH',
  V_LP_ETH_USDT = 'vETH-USDT',
  V_LP_ETH_USDC = 'vETH-USDC',
  V_LP_ETH_IPX = 'vETH-IPX',
  S_LP_USDC_USDT = 'sUSDC-USDT',
  WORMHOLE_ETH = 'ETH',
  WORMHOLE_USDC = 'USDC',
  WORMHOLE_USDT = 'USDT',
  WORMHOLE_WBNB = 'WBNB',
  WORMHOLE_WFTM = 'WFTM',
  WORMHOLE_CELO = 'CELO',
  WORMHOLE_WMATIC = 'WMATIC',
  WORMHOLE_WAVAX = 'WAVAX',
  S_LP_WORMHOLE_USDC_WORMHOLE_USDT = 'sUSDC-USDT',
  V_LP_SUI_WORMHOLE_ETH = 'vSUI-ETH',
  V_LP_SUI_WORMHOLE_USDT = 'vSUI-USDT',
  V_LP_SUI_WORMHOLE_USDC = 'vSUI-USDC',
  V_LP_SUI_WORMHOLE_WBNB = 'vSUI-WBNB',
  V_LP_SUI_WORMHOLE_WFTM = 'vSUI-WFTM',
  V_LP_SUI_WORMHOLE_WMATIC = 'vSUI-WMATIC',
  V_LP_SUI_WORMHOLE_WAVAX = 'vSUI-WAVAX',
  V_LP_SUI_WORMHOLE_CELO = 'vSUI-CELO',
}
